version: '3'
services:

  db:
    image: postgres:latest
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=statsservice
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  statsservice:
    build: .
    working_dir: /statsservice
    tty: true
    environment:
        - FLASK_APP=runserver.py
        - FLASK_ENV=development
    command: "./wait-for-postgres.sh db"
    volumes:
        - .:/statsservice:rw
    ports:
        - "5000:5000"
    expose:
        - "5000"
    depends_on:
      - db
