version: '3'
services:

  db:
    image: postgres:latest
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=statsservice
    ports:
      - '5532:5432'
    expose:
      - '5532'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  statsservice:
    build: .
    working_dir: /statsservice
    tty: true
    environment:
        - FLASK_APP=runserver.py
        - FLASK_ENV=development
    command:
        - /bin/sh
        - -c
        - |
            poetry run start
    volumes:
        - .:/statsservice:rw
    ports:
        - "5000:5000"
    depends_on:
      - db:
        condition: service_healthy
