version: '3'
services:

  db:
    image: postgres:latest
    hostname: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=statsservice
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  statsservice:
    build: .
    working_dir: /statsservice
    tty: true
    environment:
        - FLASK_APP=runserver.py
        - FLASK_ENV=development
        - FLASK_RUN_HOST=0.0.0.0
        - FLASK_RUN_PORT=5000
        - STATS_CONFIG=docker.py
    command: "./wait-for-postgres.sh db"
    volumes:
        - .:/statsservice:rw
    ports:
        - "5000:5000"
    expose:
        - "5000"
    depends_on:
      - db

volumes:
  postgres_data:
