[tool.poetry]
name = "stats-service"
version = "0.1.0"
description = "Stats API for MONARC."
authors = ["Cédric Bonhomme <cedric@cedricbonhomme.org>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1.2"
requests = "^2.23.0"
pandas = "^1.0.4"
flask_restx = "^0.2.0"
jsonschema = "^3.2.0"
Flask-SQLAlchemy = "^2.4.3"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
sphinx = "^3.0.3"
flake8 = "^3.7.9"
sphinx_rtd_theme = "^0.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
