[tool.poetry]
name = "stats-api"
version = "0.1.0"
description = "Stats API for MONARC."
authors = ["Cédric Bonhomme <cedric@cedricbonhomme.org>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1.2"
flask-mongoengine = "^0.9.5"
Flask-MongoRest = "^0.3.0"
mimerender = "^0.6.0"
cleancat = "^0.7.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
